version: "3.9"
services:
  fft_boxing:
    build:
      context: .
      dockerfile: Dockerfile 
    image: wcsng-36.ucsd.edu/fft_boxing:${FFT_BOXING_VERSION}
    container_name: fft_boxing
    shm_size: '12248mb'
    mac_address: 02:42:ac:11:00:03 # license file generated for this mac
    ipc: "host"
    networks:
      - nw
      - dns-proxy_nw
      - nomad_scisrs_nw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /home/skadaveru/Projects/scisrs/datacollect/ucsd_datacollect/data:/home/scisrs/fft_boxing/data:rw
    privileged: true
    user: 1006:1006
    working_dir: /home/scisrs/fft_boxing/
    environment:
      - BASEPATH=/home/scisrs/fft_boxing/data
      - TIME_SLICE=0.1
    command:  tail -f /dev/null

networks:
  nw:
    driver: bridge
  dns-proxy_nw:
    external: true
  nomad_scisrs_nw:
    external: true

    # external: true    